<a href="https://colab.research.google.com/github/twotablepush/AiBasic/blob/main/05_%EC%84%B1%EB%8A%A5%EC%B8%A1%EC%A0%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 혼동 행렬 confusion matrix

부류 별로 옳은 분류와 틀린 분류의 개수를 기록한 행렬
- nij는 모델이 i라고 예측했는데 실제 부류는 j인 샘플의 개수 행 : 예측한 부류, 열 : 참값
- 이진 분류에서 긍정과 부정
 - 검출하고자 하는 것이 긍정(환자가 긍정이고 정상인이 부정, 불량품이 긍정이고 정상이 부정)
- 참 긍정(TP), 거짓 부정(FN), 거짓 긍정(FP), 참 부정(TN)의 네 경우

널리 쓰이는 성능 측정 기준
- 정확률
- 특이도와 민감도 (의료에서 주로 사용)
- 정밀도와 재현률 (정보검색에서 주로 사용)

주어진 데이터를 적절한 비율로 훈련, 검증, 테스트 집합으로 나누어 씀
- 모델 선택 포함 : 훈련/검증/테스트 집합으로 나눔
- 모델 선택 제외 : 훈련/테스트 집합으로 나눔


In [ ]:
# 필기 숫자 인식 - 훈련 집합으로 학습하고 테슨트 집합으로 성능 측정

from sklearn import datasets
from sklearn import svm
from sklearn.model_selection import train_test_split
import numpy as np

# 데이터셋을 읽고 훈련 집랍과 테스트 집합으로 분할
digit = datasets.load_digits()
x_train, x_test, y_train, y_test = train_test_split(digit.data, digit.target, train_size = 0.6)

# svm의 분류 모델 SCV를 학습
s = svm.SVC(gamma = 0.001)
s.fit(x_train, y_train)

res = s.predict(x_test)

# 혼돈 행렬 구함
conf = np.zeros((10, 10))
for i in range(len(res)):
  conf[res[i]][y_test[i]] += 1
print(conf)

# 정확률 측정하고 출력
no_correct = 0
for i in range(10):
  no_correct += conf[i][i]
accuracy = no_correct/len(res)
print("테스트 집합에 대한 정확률은 ", accuracy*100, "%입니다.")

[[61.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 71.  0.  0.  0.  0.  0.  0.  2.  0.]
 [ 0.  0. 73.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 75.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0. 73.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 73.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0. 81.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0. 65.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. 74.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  1.  0. 66.]]
테스트 집합에 대한 정확률은  99.02642559109874 %입니다.


## 교차 검증

훈련/테스트 집합 나누기의 한계
- 우연히 높은 정확률 도는 우연히 낮은 정확률 발생 가능성

k-겹 교차 검증
- 훈련 집합을 K개 부분집합으로 나누어 사용 한 개를 남겨두고 k-1개로 학습한 다음 남겨둔 것으로 성능 측정 k개의 성능을 평균하여 신뢰도 높임

digit 데이터에 교차 검증 적용(모델 선택 제외)



In [ ]:
# 필기 숫자 인식 - 교차 검증으로 성능 측정

from sklearn import datasets
from sklearn import svm
from sklearn.model_selection import cross_val_score
import numpy as np

digit = datasets.load_digits()
s = svm.SVC(gamma = 0.001)
accuracies = cross_val_score(s, digit.data, digit.target, cv = 5) # 5-겹 교차 검증

print(accuracies)
print("정확률(평균) = %0.3f, 표준편차 = %0.3f" %(accuracies.mean()*100, accuracies.std()))

[0.975      0.95       0.98328691 0.99164345 0.96100279]
정확률(평균) = 97.219, 표준편차 = 0.015
