<a href="https://colab.research.google.com/github/twotablepush/AiBasic/blob/main/08_%EB%94%A5%EB%9F%AC%EB%8B%9D%2C_%ED%85%90%EC%84%9C%ED%94%8C%EB%A1%9C_%EA%B0%9C%EB%85%90.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 딥러닝의 기술 혁신 요인

- 값싼 GPU 등장
 - 10 ~ 100배의 속도 향상으로 학습 시간 단축

- 데이터셋 커짐
 - 인터넷을 통한 데이터 수집과 레이블링 ex) 1,400만장을 담은 ImageNet

- 학습 알고리즘의 발전
 - ReLU 활성 함수
 - 규제 기법(가중치 감쇠, 드롭아웃, 조기 멈춤, 데이터 증대, 앙상블 등)
 - 다양한 손실 함수와 옵티마이저 개발

 ## 딥러닝으로 인한 인공지능의 획기적 발전

 - 2010년대에 딥러닝의 성공 사례 발표 ex) Alexnet
 - 고전적인 기계학습을 사용하던 연구 그룹이 딥러닝으로 전환
 - 낮은 성능 때문에 대학 실험실에 머물던 프로토타입 시스템에 획기적인 성능 향상
 - 뛰어난 인공지능 제품이 시장에 속속 등장하여 '인공지능 붐' 조성
 - 딥러닝은 인공지능을 구현하는 핵심 기술로 자리잡음

## 대표적인 딥러닝 소프트웨어

- 텐서플로와 파이토치가 대세
- 대략 텐서플로는 기업, 파이토치는 대학 연구자들이 많이 사용



In [ ]:
# 텐서플로 버전과 동작확인
import tensorflow as tf

print(tf.__version__)
a = tf.random.uniform([2, 3], 0, 1)
print(a)
print(type(a))

2.17.0
tf.Tensor(
[[0.5081594  0.11198938 0.91657686]
 [0.31414497 0.50818694 0.40287566]], shape=(2, 3), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [ ]:
# 텐서플로와 넘파이의 호환
import tensorflow as tf
import numpy as np

t = tf.random.uniform([2, 3], 0, 1)
n = np.random.uniform(0, 1, [2, 3])
print("tensorflow로 생성한 텐서:\n", t, "\n")
print("numpy로 생성한 ndarray:\n", n, "\n")

res = t + n   # 텐서 t와 ndarray n의 덧셈
print("덧셈 결과:\n", res)

tensorflow로 생성한 텐서:
 tf.Tensor(
[[0.7976972  0.49836588 0.20671594]
 [0.85579944 0.12357414 0.17119074]], shape=(2, 3), dtype=float32) 

numpy로 생성한 ndarray:
 [[0.56613029 0.29646942 0.25343931]
 [0.63905208 0.35739052 0.2585393 ]] 

덧셈 결과:
 tf.Tensor(
[[1.3638275  0.7948353  0.46015525]
 [1.4948516  0.48096466 0.42973003]], shape=(2, 3), dtype=float32)


## 딥러닝에서 텐서

- 다차원 배열을 텐서라 부름
 - 데이터를 텐서로 표현
 - 신경망의 가중치(매개변수)를 텐서로 표현
- 넘파이는 ndarry 클래스, 텐서플로는 Tensor 클래스로 표현. 둘은 호환됨

## 0~4차원 구조의 텐서의 예
- 1차원 : iris 샘플 하나
- 2차원 : iris 샘플 여러개, 명암 영상 한 장
- 3차원 : 명암 영상 여러 장, 컬러 영상 한 장
- 4차원 : 컬러 영상 여러 장, 컬러 동영상 하나
- 5차원 : 컬러 동영상 여러

In [ ]:
import tensorflow as tf
import tensorflow.keras.datasets as ds

# MNIST 읽고 텐서 모양 출력
(x_train, y_train), (x_test, y_test) = ds.mnist.load_data()
yy_train = tf.one_hot(y_train, 10, dtype = tf.int8) # 원핫 코드로 변환
print("MNIST: ", x_train.shape, y_train.shape, yy_train.shape)

# CIFAR-10 읽고 텐서 모양 출력
(x_train, y_train), (x_test, y_test) = ds.cifar10.load_data()
yy_train = tf.one_hot(y_train, 10, dtype = tf.int8)
print("CIFAR-10: ", x_train.shape, y_train.shape, yy_train.shape)

# Boston Housing 읽고 텐서 모양 출력
(x_train, y_train), (x_test, y_test) = ds.boston_housing.load_data()
print("Boston Housing: ", x_train.shape, y_train.shape)

# Reuters 읽고 텐서 모양 출력
(x_train, y_train), (x_test, y_test) = ds.reuters.load_data()
print("Reuters: ", x_train.shape, y_train.shape)

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
MNIST:  (60000, 28, 28) (60000,) (60000, 10)
170498071/170498071 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step
CIFAR-10:  (50000, 32, 32, 3) (50000, 1) (50000, 1, 10)
57026/57026 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
Boston Housing:  (404, 13) (404,)
2110848/2110848 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
Reuters:  (8982,) (8982,)
